export const currencies = [
    { code: 'USD', symbol: '$', name: 'US Dollar', region: 'Global' },
    { code: 'EUR', symbol: '€', name: 'Euro', region: 'Europe' },
    { code: 'GBP', symbol: '£', name: 'British Pound', region: 'UK' },
    { code: 'INR', symbol: '₹', name: 'Indian Rupee', region: 'India' },
    { code: 'JPY', symbol: '¥', name: 'Japanese Yen', region: 'Japan' },
    { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', region: 'Australia' },
    { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', region: 'Canada' },
    { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', region: 'Bangladesh' },
    { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', region: 'China' },
    { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', region: 'Singapore' },
    { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', region: 'UAE' },
    { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', region: 'Saudi Arabia' },
    { code: 'RUB', symbol: '₽', name: 'Russian Ruble', region: 'Russia' },
    { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', region: 'Brazil' },
    { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', region: 'Switzerland' },
    { code: 'TRY', symbol: '₺', name: 'Turkish Lira', region: 'Turkey' },
    { code: 'KRW', symbol: '₩', name: 'South Korean Won', region: 'Korea' },
    { code: 'ZAR', symbol: 'R', name: 'South African Rand', region: 'S. Africa' },
    { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', region: 'Pakistan' },
    { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', region: 'Egypt' },
];
